### ISSUE TITLE
AddForecast returns a forecast

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#12]
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/06aad7da4900277b4b9affe7bc4885b8f1965312/src/main/java/hec/ensemble/Watershed.java#L21

why does AddForecast return a Forecast? why not return a state of success or fail?

**Comment by ktarbet** [comment]
This method is also creating a Forecast, so It can be handed back.

**Comment by HenryGeorgist** [comment]
It seems like the name for the method is a bit incongruent with providing a constructed forecast. I also feel like there is a duality to this method that is not necessary.

I would recommend a refactoring of this, there are a few ideas I have for that:
1. create a static method on forecast to create a forecast (builder pattern)
2. create a static method on watershed to create a forecast, and call that during add forecast
3. create a private method to create a forecast internal to watershed, and access that during add forecast.

this has two main questions behind it:
1. how do we wish for people to create a forecast
2. what do we intend AddForecast (and more generally, the Watershed class) to do?

Another important question is this:
is the watershed an attribute of a forecast, or is it something that contains locations and forecasts - maybe we should not develop these objects based on the structure of the RFC CSV files any longer, and rather focus on the best structure for the data in memory.

**Comment by ktarbet** [comment]
closing this because we don't have 'forecasts' after the latest refactor.
