### ISSUE TITLE
Scripting Help: Convert CNFRC CSV to sqlite database

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/FIRO_TSEnsembles#163]
I am trying to script against the `FIRO_TSEnsembles-1.0.1.jar` and am not sure what is going wrong.  

The code below creates a sqlite database and writes an empty `hec.ensemble.EnsembleTimeSeries` to the database. I suspect something is going wrong with the `CsvEnsembleReader`

Here is an example file I am trying to read:

[1986020112_american_hefs_csv_hourly.zip](https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/files/11500584/1986020112_american_hefs_csv_hourly.zip)

```python


from glob import glob
import sys
from hec.ensemble import CsvEnsembleReader, RfcCsvFile
from java.time import ZonedDateTime, ZoneId
from java.text import SimpleDateFormat
from hec import SqliteDatabase
from java.util import TimeZone
from org.sqlite import JDBC


def getJavaTimeForFile(fileDateStr):
    year = int(fileDateStr[:4])
    month = int(fileDateStr[4:6])
    day = int(fileDateStr[6:8])
    hour = int(fileDateStr[8:])
    t = ZonedDateTime.of(year, month, day, hour, 0,0,0, ZoneId.of("GMT"))
    return t

def main():

    ensembleFiles = glob(r"C:\workspace\git_clones\folsom-hindcast-processing\data\1986_scalings\200\*hourly.csv")


    dbFile = SqliteDatabase("..\output\\temp.db", SqliteDatabase.CREATION_MODE.CREATE_NEW_OR_OPEN_EXISTING_UPDATE)

    for ensembleFile in ensembleFiles[:1]:

        fileDateStr = ensembleFile.split('\\')[-1].split('_')[0]
        watershedName =  ensembleFile.split('\\')[-1].split('_')[1]
        ensembleStartDate = getJavaTimeForFile(fileDateStr)

        myFile = CsvEnsembleReader(ensembleFile)
        ensembleEndDate = ensembleStartDate.plusDays(15)
        ets = myFile.Read(watershedName, ensembleStartDate, ensembleEndDate)
        dbFile.write(ets)


if __name__ == '__main__':
    main()
```

**Comment by danhamill** [comment]
I do not see anything in here that is reading from a CSV file.

https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/81d911b53f7c9d3396def42cbc2a1319f55621e9/FIRO_TSEnsembles/src/test/java/hec/ensemble/RfcCsvFileTest.java#L44-L73

**Comment by HenryGeorgist** [comment]
we read from a csv file in many tests so we wrapped it up in a method so that we didnt have duplicated code everywhere

https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/81d911b53f7c9d3396def42cbc2a1319f55621e9/FIRO_TSEnsembles/src/test/java/hec/ensemble/DatabaseGenerator.java#L17

The CSV format is very specific, it should be in the format of the CRNFC HEFS data that is zipped. 

Here are our stored resources that these tests ultimately point at:
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/tree/81d911b53f7c9d3396def42cbc2a1319f55621e9/FIRO_TSEnsembles/src/test/resources/hefs_cache

verify your formats are the same as those.

**Comment by danhamill** [comment]
The hefs files I have two time series types (identified on the second line of the csv file):

1. QINE (simulated time series adjusted to ground observations)
2. SQIN (simulated time series)

The files withing the hefs_cache only have one time series type:
1. QINE 

Other than that, they appear to be consistent.  Both files are from the CNFRC.

**Comment by HenryGeorgist** [comment]
in your python code is there myfile null or any other problems? what is the problem you are observing (can you give me some detail?)

**Comment by ktarbet** [comment]
I think you need to set the time to '12:00:00 PM' to match the time in the file.

**Comment by danhamill** [comment]
Sure.  

In the jython script I am seeing:

myfile is an `hec.ensemble.CsvEnsembleReader` object but does not appear to be correctly initalized properly.  I am not able to see `myFile.pathToCSV` as its attribute

Here is a screenshot of my watches:

![image](https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/assets/11522898/cea74db1-9c4f-482c-9bad-bc49a73ddec4)

@ktarbet See above, but I believe I have `ensembleStartDate` and `ensembleEndDate` properly being parsed from the file name.

**Comment by HenryGeorgist** [comment]
pathToCSV is private, so you shouldnt have access to it.

**Comment by HenryGeorgist** [comment]
start date refers to the date on the file for the first file you want to read. end date is the date on the last file you want to read. it is a representation of a time series of ensemble time series... so day 1 with 64 traces that span 15 days, day 2 with 64 traces that span 15 days ...

so start and end date is the time range range of forecasts (which span a time like 15 to 30 days or something like that) you want to process.

**Comment by HenryGeorgist** [comment]
put in feature requests for things that would make your life easier... Supporting more types, adding documentation, providing access to properties etc.

**Comment by danhamill** [comment]
Will do,  at this point I think we should start building out a wiki to provide examples of how to use these tools.

I am happy to provide contributions.

**Comment by danhamill** [comment]
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/wiki/Processing-Ensemble-Files-to-SQLite-database
