### ISSUE TITLE
Subset SQLite datebase to contatin first member for each location

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/FIRO_TSEnsembles#170]
Is is possible to query the SQLite database to extract the first member for each location and each issue date?

**Comment by HenryGeorgist** [comment]
with coding anything is possible 😏 

the ensemble data is stored in a single record representing a forecast location and issuance date, the members are stored in a byte blob. the issue with that on a typical query is that you have to pull in the entire blob and parse it.

so that makes it kinda hard to write a direct query to reliably pull only the first ensemble member.

**Comment by MikeNeilson** [comment]
There's some limited support for stored procedures in SQLite but it would reduce portability. If it needed to be able to be done directly storing the data as JSON or XML, for which SQLite has tools to parse it would be practical.

That said, given the intended use of SQLite, yanking the whole think *is* probably the best bet and most performant, but you would write a wrapper to handle that usage if your application needs it a lot.

**Comment by MikeNeilson** [comment]
Curiosity, what is the usage of only getting the first (or perhaps the nth) member causing you to desire this change?

**Comment by HenryGeorgist** [comment]
the result of getting an ensemble is an orderd array of the members (which are arrays of forecasted values across time). so you just pull the 0'th array and you have your 1st member. no need for a computable

**Comment by HenryGeorgist** [comment]
use getEnsemble(location, zoneddatetime) and then you get an Ensemble. then use getValues() on the ensemble

https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/e8b72223bfa5d6f92bb0ee273fa2887e2bb95af4/FIRO_TSEnsembles/src/main/java/hec/ensemble/Ensemble.java#L68

**Comment by danhamill** [comment]
@HenryGeorgist @eheisman @MikeNeilson Thanks for the quick input.  

For this purpose, I like the 

```python
db = SqliteDatabase(dbFile, SqliteDatabase.CREATION_MODE.OPEN_EXISTING_UPDATE)
recordID = RecordIdentifier("american.FOLC1F","flow")
date = ZonedDateTime.of(1986,2,1,12,0,0,0,ZoneId.of("GMT"))
ts = db.getEnsemble(recordID, date)
firstMember = ts.getValues()[0]
```
