### ISSUE TITLE
Database Versions

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/FIRO_TSEnsembles#172]
`EnsembleTimeSeries` takes a version string in its constructor.

https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/e9d0f45d93f044189e14b35a8551511e6540e11b/FIRO_TSEnsembles/src/main/java/hec/ensemble/EnsembleTimeSeries.java#L42-L48

When you write the `EnsembleTimeSeries` to a database, the version string in its constructor appears to be overwritten in the database by a hard coded sting in the sql file that creates the tables:

https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/e9d0f45d93f044189e14b35a8551511e6540e11b/FIRO_TSEnsembles/src/main/resources/update_20200227_to_20210922.sql#L3

All of the `SqliteDatabase` version methonds (i.e., `.getVersion()`, or `.getVersions()`) appear to access the version table and not the version in a view.

## Jython example

```
recordID = RecordIdentifier("american.FOLSOM","flow")
newEts = EnsembleTimeSeries(recordID, 'cfs', 'PER-AVER', 'test')
newDb = SqliteDatabase(newDbFileName, SqliteDatabase.CREATION_MODE.CREATE_NEW_OR_OPEN_EXISTING_UPDATE)
singleMember = array([F, [array('f', [15046.7197265625, 15044.16015625, 15040.4501953125, ...])])
issueDate = ZonedDateTime.of(1986,2,13,12,0,0,0,ZoneId.of("GMT"))
newEnsemble = Ensemble(issueDate, singleMember, e.startDateTime()[0], Duration.ofHours(1), 'cfs' )
newEts.addEnsemble(newEnsemble)
newDb.write(newEts)
``` 

Browsing the database I see the `test` version the the view `view_ensemble`:

![image](https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/assets/11522898/dc1de2cb-ad78-48ff-a0d5-d2f4f93ce4a2)

How can I query the database to access a particular version found in `view_ensemble`?

**Comment by ktarbet** [comment]
Hi @danhamill ,

The Java API doesn't yet have a method for that.

```java
newDb.getEnsembleTimeSeries(recordID,issueDate,issueDate) // current implementation 
newDb.getEnsembleTimeSeries(recordID,issueDate,issueDate, version)  //  Are you looking to do something like this?
```

Looking at the code I'm not sure what will happen if there are multiple versions, and you call the method above. You might be both versions mixed together.


Note: there are two variables called version
 *  version of the database schema (in a table called version) , used for example, when we add tables or columns to the database structure.
 * version of the EnsembleTimeSeries; in your example this was 'test'

**Comment by danhamill** [comment]
@ktarbet I just put in a pull request.
