### ISSUE TITLE
Add Method to delete all ensembles from a database

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/FIRO_TSEnsembles#178]
I am needing a method to delete all ensembles from a database.  I am working on a process where a `template.db` is populated for a headless ResSim compute.  After the compute I have been having troubles deleting `template.db` because there is an unknown file lock on it.  I suspect it might be locked from the headless ResSim script I am running.  

I can think of two ways to implement this:

1. as a resource sql script
2. as a prepared statement in SQLite

Number one would look like:

```sql
DELETE from ensemble;
DELETE from ensemble_timeseries;
```

number two could be something a `deleteAllEnsemblesFromDB` method in `hec.SqliteDatabase`

```java
    public void deleteAllEnsembles() throws Exception{
        if (ps_drop_ensemble == null) {
            String sql1 = "DELETE from ensemble";
            ps_drop_ensemble = _connection.prepareStatement(sql1);
            String sql2 = "DELETE from ensemble_timeseries";
            ps_drop_ensemble_timeseries = _connection.prepareStatement(sql2);
        }
        if (ps_drop_ensemble_timeseries == null) {
            String sql2 = "DELETE from ensemble_timeseries";
            ps_drop_ensemble_timeseries = _connection.prepareStatement(sql2);
        }
        ps_drop_ensemble.execute();
        ps_drop_ensemble_timeseries.execute();
    }
```

**Comment by ktarbet** [comment]
You might try calling the SqliteDatabase.close() method to try to unlock, when done.

When the database is opened the current code uses 

```java
_connection.setAutoCommit(false);
```
We probably used above when trying to squeeze out more performance.,

We could also consider  

```java
_connection.setAutoCommit(true); // default 
```
