### ISSUE TITLE
create simple UI to browse/select a TSEnsemble

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/FIRO_TSEnsembles#20]

**Comment by HenryGeorgist** [comment]
This is intended to be a simple view that allows a user to select data from an esemble dataset. The intent is to allow this to be put into any program as a component who wishes to interact with the filetype.

**Comment by ktarbet** [comment]
Here is what I have so far:
![image](https://user-images.githubusercontent.com/4818531/76898429-e9f55d80-6852-11ea-8b56-51140f4b9952.png)
