### ISSUE TITLE
Bump Version for FIRO_TSEnsemble jar

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/FIRO_TSEnsembles#213]
There has been a decent amount of changes to the repo since the last release

- Now unit aware #195 
- Updated DB schema #173 

I am sharing these jars with an AE contractor (Folsom SOU) and I would like to supply them a version I can cite on main repo.

Can this be done?

**Comment by MikeNeilson** [comment]
I believe @dvdhoz is working getting generated artifacts pushed to hec nexus. Once that work is done you'd just have to given them the direct links to the files or dependency coordinates as needed for their own dependency management.

**Comment by danhamill** [comment]
Does that solve the versioning issue I am having?   I do not know how one tracks versions in nexus.

**Comment by MikeNeilson** [comment]
That fairly free form but we've generally be going with semantic versioning. e.g. X.Y.Z

**Comment by danhamill** [comment]
Being addressed by #222
