### ISSUE TITLE
Support Versions of the Database Schema

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#26]
the recent addition of paired data and time series data, along with the refactoring has introduced new schema that older databases created by this library do not have. This problem will likely continue into the future as more support is added. We need to know the version of the database to properly be able to handle update actions.

**Comment by ktarbet** [comment]
I really like the version update feature added by @MikeNeilson.   I used it today.

**Comment by HenryGeorgist** [comment]
@MikeNeilson is this ready to close? It seems to work for me and @ktarbet
