### ISSUE TITLE
Refactor hec/firo to hec/io for io related classes

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#3]
Since this is a library that is intended to read and write data, we need to name it according to function rather than application.

**Comment by HenryGeorgist** [comment]
This applies certainly to EnsembleDatabase.java and CSVEnsembleReader (and possibly compression related classes)- the rest may not fit in a namespace called io.

**Comment by ktarbet** [comment]
We could use the name hec.ensemble?

**Comment by HenryGeorgist** [comment]
hec.ensemble works ok for me - I feel like we should separate data structures from io related classes, but I know our current package separation mixes them both.

**Comment by ktarbet** [comment]
Lets go with hec.ensemble , since the package is still very small.  I need more insight to understand the trade off of making more namespaces, versus simplicity.

**Comment by HenryGeorgist** [comment]
noted and agreed.
