### ISSUE TITLE
Create a TimeSeriesDatabase implementation using DSS libraries

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#31]
We need to be able to read a dss file into our in memory representation (or stream...) and output it into the JdbcTimeSeriesDatabase.

**Comment by MikeNeilson** [comment]
Wouldn't this be better done in a standalone utility that includes this and javaHeclib as a dependency? If this project takes on a direct dependency of heclib it's going to complicate things. Whereas in most of the places were it will be use to cross between the two both will already be in parent programs namespace.

**Comment by HenryGeorgist** [comment]
yes. sorry. that is my intent i would like a single utility library that has dependencies on heclib and ensemble.jar to be able to act as an intermediary from one dataabase to the other.

**Comment by HenryGeorgist** [comment]
I developed a preliminary library to connect these as a plugin in WAT. [DssToSqlitePlugin](https://github.com/HydrologicEngineeringCenter/DssToSqlitePlugin)
