### ISSUE TITLE
add an iterator to EnsembleTimeSeries

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/FIRO_TSEnsembles#35]
Iterating ensembles inside EnsembleTimeSeries is not clean.

To iterate all time steps requires calling getIssueDates() then calling getEnsemble() for each issueDate

an iterator may be a better approach.

**Comment by ktarbet** [comment]
The iterator will allow changing the code in EnsembleUtility.java 
from:
``` 
        for (ZonedDateTime t: ets.getIssueDates()){
                Ensemble e = ets.getEnsemble(t);
                for(float[] v : e.getValues()){
                    for (int i = 0; i <v.length ; i++) {
                        v[i] = v[i]+10 ;// offset by 10
                    }
                }
            }
```

to
```
     for(Ensemble e : ets){               
                for(float[] v : e.getValues()){
                    for (int i = 0; i <v.length ; i++) {
                        v[i] = v[i]+10 ;// offset by 10
                    }
                }
            }
```

**Comment by ktarbet** [comment]
I think we need to add an interface, to document the similarities  between EnsembleTimeSeries and EnsembleTimeSeriesReader

```
interface IEnsembleTimeSeries {

    public Ensemble getEnsemble(ZonedDateTime issueDate);
    public String getUnits();
    public String getDataType();
    public String getVersion();
    public TimeSeriesIdentifier getTimeSeriesIdentifier();
    
}

``

**Comment by HenryGeorgist** [comment]
That iterator example looks beautiful.

**Comment by HenryGeorgist** [comment]
I generally like the idea of designing with interfaces, but i am not sure why you reference the similarities between it and the reader. Can you tell me more?

**Comment by ktarbet** [comment]
Interface may be the right language to use.  When translating to use the iterator,  there was other code that was building a new EnsembleTimeSeries.   That code would translate better if we EnsembleTimeSeries and EnsembleTimeSeriesReader had the same methods.

**Comment by HenryGeorgist** [comment]
Ok, same methods? Or do you mean that ensembleTimeSeries has a set of reliable methods that are implemented? We dont want to duplicate code certainly.

**Comment by ktarbet** [comment]
The interface methods will be implemented both EnsembleTimeSeries and EnsembleTimeSeriesReader.

**Comment by ktarbet** [comment]
@HenryGeorgist Thanks for the call.  I like the simplification of assuming enough memory, for now, and using the Decorator pattern to wrap the EnsembleTimeSeries inside the EnsembleTimeSeriesIterator.
