### ISSUE TITLE
refactor EnsembleDatabase naming

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#4]
The Ensemble Database class provides two major publicly facing functions Write(hec.firo.Watershed watershed) and Read(string watershed, localDateTime start, localdatetime endtime).

It seems that generic functionality is important to encapsulate in an interface - with an implementation of sqliteEnsembleDatabaseImpl or something like that. This will allow for future flexibility.

**Comment by ktarbet** [comment]
The current EnsembleDatabase could be named OdbcEnsembleDatabase, leaving the name 'EnsembleDatabase' for the future.

**Comment by HenryGeorgist** [comment]
I like that - I would think ensembleDatabase could be the abstract class I am looking for.
