### ISSUE TITLE
Ensemble Utility looks like a test class

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#44]
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/137201d16bb0e503f647ac489770af33430b67e7/src/main/java/hec/ensemble/EnsembleUtility.java#L16

It took me awhile to find this class, it really looks like this should be in test rather than main... @ktarbet what are your thoughts?

**Comment by ktarbet** [comment]
@HenryGeorgist are you suggesting we change this to a Junit test?  It may need up to 7GB of input data.

**Comment by HenryGeorgist** [comment]
i say we build a small dataset to ensure we can run it as a junit test. The size of the data isnt the main purpose of the test, just reliability in testing the timing of doing the work, and the ability to access all of the critical elements the integration test touches.

**Comment by HenryGeorgist** [comment]
@ktarbet  do we need ensemble utility anymore?

**Comment by ktarbet** [comment]
Perhaps EnsembleUtility can be moved to the wiki, as an example for users that need to populate a database programmatically?

**Comment by HenryGeorgist** [comment]
That sounds like a great idea.
