### ISSUE TITLE
Change build to use Github Actions

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/FIRO_TSEnsembles#57]

**Comment by ktarbet** [comment]
here is a start on this issue:
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/actions/workflows/gradle.yml

**Comment by ktarbet** [comment]
Can anyone confirm the artifacts look OK using gitHub actions?

**Comment by HenryGeorgist** [comment]
I was able to download it manually successfully
