### ISSUE TITLE
rename project FIRO_Ensembles or FIRO_TSEnsembles

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#6]
Since the purpose of this project is specialized to storage of Ensemble data we need to be clear we are not attempting to create a generic time series structure (as discussed in design meetings and decision meetings). We are simply creating a structure for ensemble data and a time series of ensemble data.

**Comment by ktarbet** [comment]
Thanks. The repo has been renamed.
