### ISSUE TITLE
MeanComputable

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#61]
I would like you to implment mean computable much like i did with min computable

**Comment by Sara-HEC** [comment]
Or I can comment on #61 here.

**Comment by HenryGeorgist** [comment]
> Or I can comment on #61 here.
It is totally valid to talk about an issue in the issue thread. If you reference the issue number anywhere it gets noted (as you can see above) in the history of the issue.
