### ISSUE TITLE
Consider restructuring Read and Write to specify a location instead of a watershed

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#7]
Based on discussions in the design sessions and decision meetings we need to be able to provide a full time series of ensembles at a specified location - it seems our primary query needs to be optimized for a single location, not a full watershed.

We may want to follow up with Joan on that. Watersheds (as defined by the RFC) may not be consistent with watersheds in the CWMS national implementation, so we need to be careful in our usage of the term as well.

**Comment by ktarbet** [comment]
Here is an idea.

Will there be more than one parameter (besides flow) at a single location?  

```java
public void readSingleLocation() {
        try {
            // Assume single watershed per sqlite database.
            EnsembleDatabase db = new EnsembleDatabase("basin7.db");
            // query a list of location?
            String[] locationNames = db.getLocationNames();

            LocalDateTime issueDate = LocalDateTime.of(2020,1,1,12,0);
            Forecast forecast= db.Forecast(locationNames[2],issueDate);
        
            float[] member1 = forecast.Ensemble[0];
            LocalDateTime[] timestamps = forecast.getTimeStamps();
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
```
@tombrauer   Do you have any advice on what type of Dates to use?  I'm trying out LocalDateTime.

**Comment by HenryGeorgist** [comment]
I believe there could be more than one parameter at a location - flow or precipitation for instance.
We should prepare ourselves for those possibilities. What about a request arguments class which can be easily converted into a sql query?

**Comment by ktarbet** [comment]
We may need to improve our database schema to support multiple parameters.

**Comment by HenryGeorgist** [comment]
I am very visual, I would be interested to know what a table looks like right now. Can you provide a picture?

**Comment by ktarbet** [comment]
|column|description|
|---|---|
|id| primary key|
|issue_date| date forecast was issued|
|watershed|watershed forecast group |
|location_name|name of point location (use seriescatalog.siteid?|
|timeseries_start_date | time stamp of first data point|
|member_length| number of time series points (time,value) pairs in each member|
|member_count|number of individual timeseries in this blob|
|compressed| 1=gzipped, 0=uncompressed |
|byte_value_array| byte[] -- actual data|

**Comment by ktarbet** [comment]
We may need to add a couple more tables, or combine watershed and location_name into some type of time series id.

**Comment by HenryGeorgist** [comment]
why not have a column called parameter type and parameter unit?

**Comment by ktarbet** [comment]
other databases (Pisces, opendcs, cwms)  have support tables like : Site, parameters, series

**Comment by ktarbet** [comment]
for example CWMS has *many* tables (here is one of three tables dedicated to forecasts)
![image](https://user-images.githubusercontent.com/4818531/71700466-37484f80-2d79-11ea-8416-4ff92659ac4c.png)

**Comment by ktarbet** [comment]
@HenryGeorgist Will you please take a look at this proposed update.  I'm thinking of two database tables.


![image](https://user-images.githubusercontent.com/4818531/72022318-f773e300-3224-11ea-91e2-96a030b0e644.png)

![image](https://user-images.githubusercontent.com/4818531/72022347-09558600-3225-11ea-882b-137e991628fc.png)

**Comment by HenryGeorgist** [comment]
an entire time series of ensembles should have the same table information. consider inverting the structure  - have the ensemble keep a key to the table describing the parameters for all ensembles at a "location"

**Comment by HenryGeorgist** [comment]
actually, on closer inspection, I think that is what you are trying to do. I like this approach. Are there any concerns about this approach for you?

**Comment by ktarbet** [comment]
My only concerns are the assumptions that this makes, such as all data is the same parameter, same datatype etc for this collection of ensembles.

**Comment by HenryGeorgist** [comment]
In general the way we have been discussing a time series of ensembles is intended to represent a series of ensembles that share the same physical location and parameter across a time range - it is possible there could be a future need that has a different dimensionality to the problem, but I don't see the case right now.

**Comment by ktarbet** [comment]
I would like to drop the watershed column, and have location become a timeseries_id.  The timeseries_id is more generic and could include the watershed if the application needed it.

"watershed.location"  combined = timeseries_id
