### ISSUE TITLE
in firoplugin --  Rename OK to 'Select'

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/FIRO_TSEnsembles#70]
also test with larger data set that has multiple locations.

**Comment by HenryGeorgist** [comment]
@ktarbet the rename ok to select was merged in, but this issue was not tagged. Did you do the testing with multiple locations? It seems like we have two issues in this single issue.

**Comment by ktarbet** [comment]
Yes, I found a sqlite file with multiple locations to test.   However,  the code is designed to selecting a single location.

**Comment by HenryGeorgist** [comment]
is this issue still relevant?

**Comment by ktarbet** [comment]
This has been done.
