### ISSUE TITLE
Add CumulativeVolume to Stats

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#72]
We need to compute cumulative volume to support decision makers. This metric makes sense as a single value for each trace and for a time series of cumulative volume for each trace.
Volume technically needs to be aware of parameter and time, but if we wanted a base implementation, we could ignore and simply sum the values of the traces.

Implement Computable, and probably needs to implement Configurable, to produce the total cumulative volume for each trace.
Implement the code on MultiComputable to provide the cumulative volume for each timestep for each trace.

**Comment by Sara-HEC** [comment]
so, you're saying to assume the input to the function will be traces of volume per time step?  ?? @HenryGeorgist

**Comment by HenryGeorgist** [comment]
maybe we should not call it volume, and instead call it cumulative flow - I need to check how Beth calculated it in her spreadsheet

**Comment by HenryGeorgist** [comment]
@Sara-HEC we added units to the configuration on the branch feature/units - if we branch off of it, we should be able to use that parameter to determine source units and stage the conversion to destination units.

Right now all of our data seems to have blank units, so we need to modify our test databases to track units. When checking units we should have a default case for our units if units comes across blank.

**Comment by Sara-HEC** [comment]
still learning the process.  I attempted building a new class with some of the required features, but could really use some help from @HenryGeorgist or @dvdhoz ....
For example, I'm unsure of how to use the configuration and whether I need to add a units conversion to this class (probably not, but where will that happen?).

**Comment by HenryGeorgist** [comment]
@Sara-HEC, we are attempting to use composition to bring together interfaces that compose a capability. Configurable is an interface, you must implement it. The configuration gets set (if an object implements it) in the Ensemble class. The inputs for the configuration are then set (prior to execution of the compute method) so that we have the right units and timesteps etc at time of compute. 
I can't review your code unless it is here in the project. Create a branch and commit to the branch and tag a pull request for my review and i can comment what i think needs to change.
