### ISSUE TITLE
Componentize the radio button selector for Statistics in Ensemble View

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#92]
The selection of statistics will occur in multiple places, not just in the view where ensembles are plotted. 

The list of available statistics must depend upon the Statistics Enum. 

The selection must allow for 0 -> many Statistics Selections.

The component must fire an event to notify consumers when a selection is added or removed (which would trigger a redraw in the plotting tools, or a save in an alternative editor), in the event (if possible) send the current selection of Statistics as an array of Statistics

The component must be able to be initalized with a list of Statistics Enum. 

The component must provide access to the currently selected statistics as a property.

**Comment by sharkcooper** [comment]
This issue is addressed in d5dd305974d3027b621cc53955d98b77ed722279

**Comment by HenryGeorgist** [comment]
cool, is that closed then?
