### ISSUE TITLE
Is the CSV to Sqlite feature related to EnsembleViewer exclusively?

### ISSUE THREAD

**Issue by sharkcooper** [HydrologicEngineeringCenter/FIRO_TSEnsembles#94]
Is the capability of converting CSV files to Sqlite files exclusively for EnsembleViewer or is it intended to be its own object/function?

**Comment by HenryGeorgist** [comment]
it is related to another open ticket  #84  I think. we need a model component to do the work, but the visualization component to connect the model object is what this ticket should be tracking

**Comment by HenryGeorgist** [comment]
ticket #93  is the main view ticket.
