### ISSUE TITLE
Do CSV files hold information about parameter, units, and data type?

### ISSUE THREAD

**Issue by sharkcooper** [HydrologicEngineeringCenter/FIRO_TSEnsembles#96]
While working on #93, I realized that RfcCsvFile doesn't allow me to get the parameter, units, version, or data type of a CSV file. Is this ok? If so, the CSV data will be written with an empty parameter, units, version, and data type.

**Comment by HenryGeorgist** [comment]
there is a row in the table that is filled with the text "QINE" which I believe describes parameter and units, but I am unfamiliar.
